# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure(2) do |config|
  config.vm.box = "mwrock/Windows2016"
  config.vm.synced_folder ".", "/mapped-from-host"
  config.vm.provision :shell, path: "scripts/deploy.cmd"
  config.vm.network "forwarded_port", guest: 80, host: 8080
  config.vm.network "private_network", ip: "192.168.50.4"
end
