# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure(2) do |config|
  config.vm.box = "mwrock/Windows2016"
  config.vm.synced_folder ".", "/mapped-from-host"
  config.vm.provision :shell, path: "build.cmd"
  config.vm.network "forwarded_port", guest: 3000, host: 3000
  config.vm.network "forwarded_port", guest: 9200, host: 9200
  config.vm.network "forwarded_port", guest: 5601, host: 5601 
  config.vm.network "private_network", ip: "192.168.50.4"
end
