#!/bin/bash

# leiningen wrapper for sonar - JimG

# This script may be too clever for its own good. Its concern is to make
# leiningen work inside docker containers for sonar. The two aspects to
# this are downloading the latest script from the net if its not already
# there, and dealing with Proxy nonsense

curl https://raw.githubusercontent.com/technomancy/leiningen/stable/bin/lein > lein_script
chmod +x lein_script

if ! [[ $http_proxy == *"http"* ]]; then
  unset http_proxy;
fi

./lein_script $@